export function getMainPanel() {
    return [
        '                <section class="surface account-surface">',
        '                    <div id="loginStatus"></div>',
        '                    <div class="surface-actions">',
        '                        <button id="loginBtn" class="primary-btn full-width">Login Outlook</button>',
        '                        <button id="logoutBtn" class="danger-btn full-width" style="display:none;">Logout</button>',
        '                    </div>',
        '                    <button id="unipileBtn" class="secondary-btn full-width" type="button">Connect LinkedIn (Unipile)</button>',
        '                </section>',
        '',
        '                <section class="surface status-surface">',
        '                    <div class="affinity-row">',
        '                        <span id="affinityDealIndicator" class="affinity-indicator">Affinity status pending…</span>',
        '                        <button id="addDealPipelineBtn" class="secondary-btn" type="button" disabled>Add to Deal Pipeline</button>',
        '                    </div>',
        '                </section>',
        '',
        '                <section class="surface layout-surface">',
        '                    <div class="panel-layout">',
        '                        <div class="panel-main">',
        '                            <label>Founder Name<input id="founderName" placeholder="Founder Name"/></label>',
        '                            <label>To<input id="to" placeholder="founder-emails@company.com"/></label>',
        '                            <label>Subject<input id="subject" placeholder="Generated subject will appear here..."/></label>',
        '                            <label>Calendly Link<input id="calendly" placeholder="https://calendly.com/your-slot"/></label>',
        '                            <label>Founder LinkedIn<input id="linkedin" placeholder="https://linkedin.com/in/founder"/></label>',
        '                            <label>Partner CC<select id="partnerSelect" multiple size="4"><option disabled>Loading partners...</option></select></label>',
        '                            <div class="muted">Select partners to automatically add their emails to CC (Ctrl/Cmd-click for multi-select).</div>',
        '                            <label>CC DN Colleagues<input id="cc" placeholder="alice@dncapital.com; bob@dncapital.com"/></label>',
        '                            <button id="generateBtn" class="primary-btn full-width" disabled>Generate Email</button>',
        '                            <button id="sendBtn" class="primary-btn full-width" disabled>Send</button>',
        '                            <textarea id="emailBox" rows="10" placeholder="Generated e-mail body will appear here..."></textarea>',
        '                            <div class="muted">Note: The signature below is <b>only</b> appended when sending. It\'s not shown in the draft.</div>',
        '                            <details id="signatureSection">',
        '                                <summary>Signature settings</summary>',
        '                                <div>',
        '                                    <textarea id="signatureHtml" rows="5" placeholder="<p>Thanks,<br>First Last<br>Investor<br>DN Capital</p>"></textarea>',
        '                                    <label style="display:flex;gap:4px;margin-top:6px;">',
        '                                        <input type="checkbox" id="appendSignature" checked />',
        '                                        <span>Append signature when sending</span>',
        '                                    </label>',
        '                                </div>',
        '                            </details>',
        '                        </div>'
    ].join('\n');
}
