export function getSidebar() {
    return [
        '                        <div class="panel-sidebar">',
        '                            <section class="workflow-section" id="companyWorkflowSection">',
        '                                <h3>Workflow for this company</h3>',
        '                                <div class="workflow-step" id="followup" data-step="followup">',
        '                                    <div class="workflow-step-header">',
        '                                        <input type="checkbox" id="autoFollowUp" checked />',
        '                                        <span>Email follow-up</span>',
        '                                    </div>',
        '                                    <label>Trigger at<input type="datetime-local" id="followUpTrigger" /></label>',
        '                                    <textarea id="followUpTemplate" rows="3" placeholder="Quick nudge on this. Would love to connect for 30 minutes. Here is my Calendly: {{calendly}}"></textarea>',
        '                                </div>',
        '                                <div class="workflow-step" id="linkedin" data-step="linkedin">',
        '                                    <div class="workflow-step-header">',
        '                                        <input type="checkbox" id="linkedinFollowUpToggle" checked />',
        '                                        <span>LinkedIn request</span>',
        '                                    </div>',
        '                                    <label>Trigger at<input type="datetime-local" id="linkedinTrigger" /></label>',
        '                                    <textarea id="linkedinMessage" rows="3" maxlength="200" placeholder="Hi {{firstName}}, just sent you an email and would love to connect here as well!"></textarea>',
        '                                </div>',
        '                                <div class="workflow-step" id="partner" data-step="partner">',
        '                                    <div class="workflow-step-header">',
        '                                        <input type="checkbox" id="partnerEscalationToggle" checked />',
        '                                        <span>Forward to partner</span>',
        '                                    </div>',
        '                                    <label>Trigger at<input type="datetime-local" id="partnerTrigger" /></label>',
        '                                    <label>Partner<select id="partnerForwardSelect"><option value="">Select partner</option></select></label>',
        '                                    <textarea id="partnerMessage" rows="3" placeholder="Hi {{partnerName}}, mind taking a look at this thread and nudging the founder?"></textarea>',
        '                                </div>',
        '                            </section>',
        '',
        '                            <section class="workflow-section" id="workflowPreviewSection">',
        '                                <h3>Scheduled tasks for this company</h3>',
        '                                <ul id="currentWorkflowPreview" class="workflow-preview-list"></ul>',
        '                            </section>',
        '',
        '                            <section class="workflow-section" id="pipelineTasksSection">',
        '                                <h3>Pipeline – other companies</h3>',
        '                                <ul id="pipelineTasksList" class="workflow-preview-list"></ul>',
        '                                <p class="muted">Tasks are stored in Supabase and will trigger at the selected time.</p>',
        '                            </section>',
        '                        </div>'
    ].join('\n');
}
