export function getStyles() {
    return [
        '    <style>',
        '        :host, * {',
        '            box-sizing: border-box;',
        "            font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;",
        '            color: #0f172a;',
        '        }',
        '',
        '        :host {',
        '            font-size: 12px;',
        '        }',
        '',
        '        #specter-outreach-panel {',
        '            background-color: #F5F5F5;',
        '            border: solid 3px rgba(148, 163, 184, 0.75);',
        '            border-radius: 15px;',
        '            width: clamp(420px, 48vw, 960px);',
        '            height: clamp(560px, 70vh, calc(100vh - 32px));',
        '            min-width: 380px;',
        '            min-height: 520px;',
        '            max-width: calc(100vw - 32px);',
        '            max-height: calc(100vh - 24px);',
        '            display: flex;',
        '            flex-direction: column;',
        '            overflow: hidden;',
        '            position: relative;',
        '        }',
        '',
        '        button,',
        '        input,',
        '        optgroup,',
        '        select,',
        '        textarea,',
        '        span,',
        '        label,',
        '        summary {',
        '            font-size: 12px;',
        '        }',
        '',
        '        #specter-outreach-panel button {',
        '            border: none;',
        '            border-radius: 10px;',
        '            color: #fff;',
        '            font-weight: 600;',
        '            padding: 10px 16px;',
        '            cursor: pointer;',
        '            display: inline-flex;',
        '            align-items: center;',
        '            justify-content: center;',
        '            gap: 6px;',
        '            min-height: 40px;',
        '            width: auto;',
        '        }',
        '',
        '        #specter-outreach-panel button:disabled {',
        '            opacity: 0.6;',
        '            cursor: not-allowed;',
        '            box-shadow: none;',
        '        }',
        '',
        '        #specter-outreach-panel button.full-width {',
        '            width: 100%;',
        '        }',
        '',
        '        #specter-outreach-panel button.secondary-btn {',
        '            background: rgba(37, 99, 235, 0.12);',
        '            color: #1d4ed8;',
        '            box-shadow: none;',
        '        }',
        '',
        '        #specter-outreach-panel button.danger-btn {',
        '            background-color: #ef4444;',
        '        }',
        '',
        '        #generateBtn {',
        '            background-color: #1D4ED8',
        '        }',
        '',
        '        #sendBtn {',
        '            background-color: #1EDA1B',
        '        }',
        '',
        '        .panel-header {',
        '            color: #fff;',
        '            padding: 18px 24px 0px 24px;',
        '            display: flex;',
        '            align-items: center;',
        '            justify-content: space-between;',
        '        }',
        '',
        '        #dragHandle {',
        '            display: flex;',
        '            align-items: center;',
        '            cursor: grab;',
        '            user-select: none;',
        '            flex: 1;',
        '            min-width: 0;',
        '        }',
        '',
        '        #dragHandle:active {',
        '            cursor: grabbing;',
        '        }',
        '',
        '        .panel-heading-text {',
        '            display: flex;',
        '            flex-direction: column;',
        '        }',
        '',
        '        .panel-title {',
        '            font-size: 17px;',
        '            font-weight: 700;',
        '            letter-spacing: 0.01em;',
        '        }',
        '',
        '        .header-actions {',
        '            display: flex;',
        '            align-items: center;',
        '            gap: 12px;',
        '        }',
        '',
        '        .model-select {',
        '            display: flex;',
        '            flex-direction: column;',
        '            font-size: 12px;',
        '            font-weight: 600;',
        '            color: rgba(255, 255, 255, 0.85);',
        '        }',
        '',
        '        .model-select #modelSelect {',
        '            border-radius: 10px;',
        '            padding: 8px;',
        '            background-color: #f5f5f5;',
        '        }',
        '',
        '        .model-select select:focus {',
        '            outline: 2px solid rgba(255, 255, 255, 0.5);',
        '            outline-offset: 2px;',
        '        }',
        '',
        '        #closeBtn {',
        '            background-color: #ef4444 !important;',
        '            padding: 0 !important;',
        '            min-height: 30px !important;',
        '            width: 30px !important;',
        '        }',
        '',
        '        #closeBtn span {',
        '            font-size: 15px;',
        '            color: #fff;',
        '        }',
        '',
        '        .sr-only {',
        '            position: absolute;',
        '            width: 1px;',
        '            height: 1px;',
        '            padding: 0;',
        '            margin: -1px;',
        '            overflow: hidden;',
        '            clip: rect(0, 0, 0, 0);',
        '            border: 0;',
        '        }',
        '',
        '        .panel-body {',
        '            flex: 1;',
        '            display: flex;',
        '            flex-direction: column;',
        '            padding: 16px;',
        '            gap: 16px;',
        '            overflow: hidden;',
        '        }',
        '',
        '        .panel-scroll {',
        '            flex: 1;',
        '            overflow: auto;',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 16px;',
        '            padding-right: 4px;',
        '            margin-bottom: 10px;',
        '        }',
        '',
        '        .panel-scroll::-webkit-scrollbar {',
        '            width: 8px;',
        '        }',
        '',
        '        .panel-scroll::-webkit-scrollbar-thumb {',
        '            background: rgba(148, 163, 184, 0.6);',
        '            border-radius: 999px;',
        '        }',
        '',
        '        .panel-scroll::-webkit-scrollbar-track {',
        '            background: transparent;',
        '        }',
        '',
        '        .surface {',
        '            background: rgba(255, 255, 255, 0.85);',
        '            border-radius: 10px;',
        '            border: 1px solid rgba(226, 232, 240, 0.9);',
        '            padding: 16px;',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 14px;',
        '        }',
        '',
        '        .surface-actions {',
        '            display: grid;',
        '            grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));',
        '            gap: 10px;',
        '        }',
        '',
        '        #loginStatus {',
        '            font-size: 12px;',
        '            line-height: 1.5;',
        '        }',
        '',
        '        #loginBtn {',
        '            background-color: #1d4ed8;',
        '        }',
        '',
        '        #specter-outreach-panel input:not([type="checkbox"]),',
        '        #specter-outreach-panel textarea,',
        '        #specter-outreach-panel select {',
        '            width: 100%;',
        '            border-radius: 10px;',
        '            padding: 10px 12px;',
        '            border: 1px solid rgba(148, 163, 184, 0.45);',
        '            background: rgba(241, 245, 249, 0.8);',
        '            color: #0f172a;',
        '            resize: vertical;',
        '        }',
        '',
        '        #specter-outreach-panel textarea {',
        '        }',
        '',
        '        #specter-outreach-panel input:not([type="checkbox"]):focus,',
        '        #specter-outreach-panel textarea:focus,',
        '        #specter-outreach-panel select:focus {',
        '            border-color: #2563eb;',
        '            background: #fff;',
        '            outline: none;',
        '        }',
        '',
        '        #specter-outreach-panel input[type="checkbox"] {',
        '            accent-color: #2563eb;',
        '            width: 16px;',
        '            height: 16px;',
        '            margin: 0 6px 0 0;',
        '        }',
        '',
        '        .surface.status-surface {',
        '            padding: 16px;',
        '        }',
        '',
        '        .affinity-row {',
        '            display: flex;',
        '            align-items: center;',
        '            gap: 10px;',
        '            flex-wrap: wrap;',
        '        }',
        '',
        '        .affinity-indicator {',
        '            font-size: 12px;',
        '            padding: 6px 10px;',
        '            border-radius: 999px;',
        '            background: rgba(15, 23, 42, 0.05);',
        '            color: #1f2937;',
        '            font-weight: 600;',
        '        }',
        '',
        '        .affinity-indicator.in-pipeline {',
        '            background: rgba(16, 185, 129, 0.15);',
        '            color: #047857;',
        '        }',
        '',
        '        .affinity-indicator.not-in-pipeline {',
        '            background: rgba(248, 113, 113, 0.15);',
        '            color: #b91c1c;',
        '        }',
        '',
        '        #addDealPipelineBtn {',
        '            font-size: 12px;',
        '            padding: 8px 14px;',
        '        }',
        '',
        '        .surface.layout-surface {',
        '            padding: 0;',
        '        }',
        '',
        '        .panel-layout {',
        '            display: grid;',
        '            gap: 16px;',
        '            padding: 16px;',
        '            grid-template-columns: minmax(0, 1fr);',
        '        }',
        '',
        '        @media (min-width: 980px) {',
        '            .panel-layout {',
        '                grid-template-columns: minmax(0, 1.15fr) minmax(0, 0.85fr);',
        '            }',
        '        }',
        '',
        '        .panel-main,',
        '        .panel-sidebar {',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 14px;',
        '        }',
        '',
        '        .panel-main label,',
        '        .panel-sidebar label {',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 6px;',
        '            font-weight: 600;',
        '            color: #0f172a;',
        '        }',
        '',
        '        #emailBox {',
        '            min-height: 200px;',
        '        }',
        '',
        '        #partnerSelect {',
        '            min-height: 120px;',
        '        }',
        '',
        '        #partnerSelect option {',
        '            padding: 3px 4px;',
        '        }',
        '',
        '        .muted {',
        '            font-size: 12px;',
        '            color: #475569;',
        '            margin-top: -6px;',
        '        }',
        '',
        '        #pipelineTasksSection .muted {',
        '            margin: 0 !important;',
        '        }',
        '',
        '        details summary {',
        '            cursor: pointer;',
        '            font-weight: 600;',
        '            color: #1e293b;',
        '        }',
        '',
        '        details summary::-webkit-details-marker {',
        '            display: none;',
        '        }',
        '',
        '        details > div {',
        '            margin-top: 6px;',
        '        }',
        '',
        '        .panel-sidebar {',
        '            border-left: 1px solid rgba(148, 163, 184, 0.35);',
        '        }',
        '',
        '        .workflow-section {',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 12px;',
        '            padding-left: 16px;',
        '        }',
        '',
        '        #workflowPreviewSection, #pipelineTasksSection {',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 12px;',
        '            margin-left: 16px;',
        '            padding: 16px;',
        '            background-color: rgba(241, 245, 249, 0.8);',
        '            border-radius: 10px;',
        '        }',
        '',
        '        .workflow-section h3 {',
        '            margin: 0;',
        '            font-size: 14px;',
        '            font-weight: 700;',
        '            color: #0f172a;',
        '        }',
        '',
        '        .workflow-step {',
        '            background: #fff;',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 8px;',
        '        }',
        '',
        '        #followup {',
        '            border-bottom: 1px solid rgba(37, 99, 235, 0.18);',
        '            padding-bottom: 12px;',
        '        }',
        '',
        '        #linkedin {',
        '            border-bottom: 1px solid rgba(37, 99, 235, 0.18);',
        '            padding-bottom: 12px;',
        '        }',
        '',
        '        #partner {',
        '        }',
        '',
        '        .workflow-step-header {',
        '            display: flex;',
        '            align-items: center;',
        '            gap: 3px;',
        '            font-weight: 600;',
        '        }',
        '',
        '        .workflow-preview-list {',
        '            list-style: none;',
        '            margin: 0;',
        '            padding: 0;',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 8px;',
        '            max-height: 350px;',
        '            overflow: auto;',
        '        }',
        '',
        '        .workflow-preview-list::-webkit-scrollbar {',
        '            width: 6px;',
        '        }',
        '',
        '        .workflow-preview-list::-webkit-scrollbar-thumb {',
        '            background: rgba(148, 163, 184, 0.5);',
        '            border-radius: 999px;',
        '        }',
        '',
        '        .workflow-preview-item {',
        '            border-radius: 10px;',
        '            padding: 10px 12px;',
        '            border: 1px solid rgba(203, 213, 225, 0.7);',
        '        }',
        '',
        '        .workflow-preview-item strong {',
        '            display: block;',
        '            font-size: 12px;',
        '            margin-bottom: 4px;',
        '        }',
        '',
        '        .workflow-preview-item time {',
        '            font-size: 12px;',
        '            color: #475569;',
        '        }',
        '',
        '        .pipeline-task-item {',
        '            display: flex;',
        '            flex-direction: column;',
        '            gap: 6px;',
        '        }',
        '',
        '        .pipeline-task-header, .workflow-task-header {',
        '            display: flex;',
        '            align-items: flex-start;',
        '            justify-content: space-between;',
        '            gap: 12px;',
        '        }',
        '',
        '        .pipeline-task-company {',
        '            font-size: 12px;',
        '            color: #0f172a;',
        '            font-weight: 600;',
        '        }',
        '',
        '        .pipeline-task-message {',
        '            font-size: 12px;',
        '            color: #475569;',
        '            line-height: 1.5;',
        '        }',
        '',
        '        .pipeline-task-actions {',
        '            display: flex;',
        '            justify-content: flex-end;',
        '        }',
        '',
        '        .pipeline-task-delete-btn {',
        '            font-size: 12px;',
        '            padding: 5px 10px !important;',
        '            border-radius: 7px !important;',
        '            background: #ef4444;',
        '            width: auto;',
        '            box-shadow: none;',
        '            min-height: 30px !important;',
        '        }',
        '',
        '        .pipeline-task-delete-btn[disabled] {',
        '            opacity: 0.65;',
        '            cursor: wait;',
        '            transform: none;',
        '        }',
        '',
        '        .panel-footer {',
        '            display: flex;',
        '            justify-content: space-between;',
        '            align-items: center;',
        '            font-size: 12px;',
        '            color: #475569;',
        '        }',
        '',
        '        #status {',
        '            font-size: 12px;',
        '            color: #1f2937;',
        '            line-height: 1.5;',
        '        }',
        '',
        '        .panel-footer #status {',
        '            margin-left: 25px;',
        '        }',
        '',
        '        #resize-handle {',
        '            position: absolute;',
        '            bottom: 14px;',
        '            left: 14px;',
        '            width: 18px;',
        '            height: 18px;',
        '            cursor: sw-resize;',
        '            background: repeating-linear-gradient(45deg, rgba(148, 163, 184, 0.85) 0px, rgba(148, 163, 184, 0.85) 3px, transparent 3px, transparent 6px);',
        '            border-radius: 4px;',
        '            opacity: 0.8;',
        '        }',
        '',
        '        @media (max-width: 768px) {',
        '            .header-actions {',
        '                flex-direction: column;',
        '                align-items: flex-end;',
        '            }',
        '',
        '            .model-select select {',
        '                width: 100%;',
        '            }',
        '',
        '            #specter-outreach-panel {',
        '                width: min(94vw, 640px);',
        '                min-width: min(94vw, 420px);',
        '            }',
        '',
        '            .panel-body {',
        '                padding: 18px;',
        '            }',
        '        }',
        '    </style>'
    ].join('\n');
}

